### PR TITLE
[FIX] Fix issue with enumeration as default value in CLI

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Should fix the error `TypeError: EnumType.call() missing 1 required positional argument: 'value'` when using the ADNI-to-BIDS converter without any modality.
Recently introduced in #1140

### CODE REVIEW

**Review by AliceJoubert — APPROVED** [review]
All good, thanks @NicolasGensollen !!
